[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry-server"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  publish = "dist"
